### ISSUE TITLE
PMIx_Fence data collection collisions 

### ISSUE THREAD

**Issue by artpol84** [open-mpi/pmix#34]
Hello,
PMIx_Fence API provides ability to ask/not-ask for data collection. However there is no protection against conflicting requests, i.e. if rank=0 will ask for data while rank=1 would want to perform empty barrier. In this case rank=0 will submit data (that rank=1 doesn't want to see) and rank=0 won't provide the data (while rank=0 is willing to have them).

In [current implementation](https://github.com/open-mpi/pmix/blob/5cdfe465896734273403771ed23d3b786138a255/src/server/pmix_server_ops.c#L444) inside the host the last requestor wins and dictates the exchange mode. Inter-node exchange will be performed correctly from technical point of view (no error will be detected). However there is no guarantee that all nodes have the same data_collection value.

My position is that we need to track this problem and rise an error in this case. This would help developers who will use PMIx. I can implement this logic if everybody is OK with that. It won't introduce any overhead.

**Comment by rhc54** [comment]
You obviously can’t check it globally as a separate step, but I guess you are saying that:

* each server should check that it matches across all its clients (however, be sure that the server still participates in the global fence op regardless so that we don’t hang), and

* the fence collective itself should include the collect_data flag so everyone can check to see if it matches?

And then return an error if anyone differs? I guess that makes sense - go ahead!

**Comment by artpol84** [comment]
Yes, this was my idea.

**Comment by rhc54** [comment]
Kewl - sounds good!

**Comment by artpol84** [comment]
Fixed
